modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/CosmicDan-Minecraft/SimpleDayLengthExtender/issues"
license = "LGPLv3"

[[mods]]
modId = "simpledaylengthextender"
version = "${version}"
displayName = "Simple Day Length Extender"
authors = "CosmicDan"
description = '''
A simple yet compatible mod to extend the day and/or night length in Minecraft. Works by switching the doDaylightCycle gamerule on and off internally, without the need for command blocks (and without any log-spam)

https://www.curseforge.com/minecraft/mc-mods/simple-day-length-extender
'''
logoFile = "logo.png"

[[dependencies.simpledaylengthextender]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.simpledaylengthextender]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "simpledaylengthextender.mixins.json"
